// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AdventureRoller.DatabaseContext
{
    public partial class Characters
    {
        public Characters()
        {
            CharacterAttributes = new HashSet<CharacterAttributes>();
        }

        public Guid CharacterId { get; set; }
        public decimal DiscordId { get; set; }
        public string Name { get; set; }
        public string Edition { get; set; }
        public bool Active { get; set; }
        public int Level { get; set; }

        public virtual ICollection<CharacterAttributes> CharacterAttributes { get; set; }
    }
}