// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AdventureRoller.DatabaseContext
{
    public partial class Editions
    {
        public string Edition { get; set; }
        public string AttributeNo { get; set; }
        public string AttributeName { get; set; }
    }
}