// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AdventureRoller.DatabaseContext
{
    public partial class AdventurerollerdbContext : DbContext
    {
        public AdventurerollerdbContext()
        {
        }

        public AdventurerollerdbContext(DbContextOptions<AdventurerollerdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CharacterAttributes> CharacterAttributes { get; set; }
        public virtual DbSet<Characters> Characters { get; set; }
        public virtual DbSet<Editions> Editions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CharacterAttributes>(entity =>
            {
                entity.HasKey(e => new { e.CharacterId, e.CharacterLevel, e.Name })
                    .HasName("PK_CharacterAttributes_CharacterId");

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.Dice).HasMaxLength(25);

                entity.Property(e => e.Value)
                    .IsRequired()
                    .HasMaxLength(70);

                entity.HasOne(d => d.Character)
                    .WithMany(p => p.CharacterAttributes)
                    .HasForeignKey(d => d.CharacterId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Character__Chara__619B8048");
            });

            modelBuilder.Entity<Characters>(entity =>
            {
                entity.HasKey(e => e.CharacterId)
                    .HasName("PK_Characters_CharacterId");

                entity.Property(e => e.CharacterId).ValueGeneratedNever();

                entity.Property(e => e.DiscordId).HasColumnType("numeric(20, 0)");

                entity.Property(e => e.Edition)
                    .IsRequired()
                    .HasMaxLength(5);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Editions>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.AttributeName)
                    .IsRequired()
                    .HasMaxLength(15);

                entity.Property(e => e.AttributeNo)
                    .IsRequired()
                    .HasMaxLength(13);

                entity.Property(e => e.Edition)
                    .IsRequired()
                    .HasMaxLength(10);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}